services:
  zookeeper:
    image: zookeeper:3.6
    ports: ["2181:2181"]

  provider:
    build: .
    environment:
      DUBBO_REGISTRY_ADDRESS: zookeeper://zookeeper:2181
    command: >
      java -Dloader.main=com.example.test4.ProviderApp
           -Dorg.apache.commons.collections.enableUnsafeSerialization=true
           -Dspring.config.name=application-provider
           -Ddubbo.registry.address=${DUBBO_REGISTRY_ADDRESS:-zookeeper://zookeeper:2181}
           -jar /app/app.jar
    ports: [ "20880:20880","8081:8081", "9000:9000"]

  consumer:
    build: .
    environment:
      DUBBO_REGISTRY_ADDRESS: zookeeper://zookeeper:2181
    command: >
      java -Dloader.main=com.example.test4.ConsumerApp
           -Dspring.config.name=application-consumer
           -Ddubbo.registry.address=${DUBBO_REGISTRY_ADDRESS:-zookeeper://zookeeper:2181}
           -jar /app/app.jar
    ports: [ "8899:8899" ]