spring:
  application.name: provider
server:
  port: 8081

dubbo:
  application:
    name: provider
  registry:
    address: ${DUBBO_REGISTRY_ADDRESS:zookeeper://zookeeper:2181}
  protocol:
    name: http
    port: 9000
  scan:
    base-packages: com.example.test4
